export const itemImages = new Map([
  ["Redwood", "redwood.jpg"],
  ["Turf", "turf.jpg"],
  ["Fountain", "fountain.jpg"],
  ["Pool", "pool.jpg"],
  ["Pirate Ship", "pirateShip.jpg"],
  ["Taj Mahal", "tajMahal.jpg"],
  ["Pergola", "pergola.jpg"],
  ["3-5", "3-5.jpg"],
  ["16+", "16+.jpg"],
  ["6-15", "6-15.jpg"],
  ["Pavers", "pavers.jpg"],
  ["Gravel", "gravel.jpg"],
  ["Composite", "composite.jpg"],
  ["Bamboo Shroud", "bambooShroud.jpg"],
  ["Redwood Fence", "redwoodFence.jpg"],
  ["Plywood Fence", "plywoodFence.jpg"],
]);
