export const sectionTitleFormat = new Map([
  ["WATER_FEATURES", "WATER FEATURES"],
  ["STRUCTURES", "STRUCTURES"],
  ["LIGHTING", "LIGHTING"],
  ["GROUND_COVER", "GROUND COVER"],
  ["DECK MATERIAL", "DECK MATERIAL"],
  ["FENCING_AND_PRIVACY", "FENCING AND PRIVACY"],
]);
